### ISSUE TITLE
idempotencyKey vs idempotency_key

### ISSUE THREAD

**Issue by MordantWastrel** [jcberquist/stripe-cfml#20]
The README refers to `idempotencyKey` that can be sent either as a header or a request param.

The API docs define it as `idempotency_key`. 

The code for headers.cfc has `idempotency_key`.

Should the README have an underscore in there?

**Comment by jcberquist** [comment]
Either will work. You can pass `idempotency_key` or `idempotencyKey` to a method and it will be treated the same way. This is also true of the other arguments that get passed to the API as headers such as `stripeAccount` and `apiVersion`. 

The API documentation does describe it as `idempotency_key`, but the examples taken from their SDKs vary. For instance, that is the format used for their Python SDK, while the Node version has it as `idempotencyKey`. No matter how the SDKs accept the argument, in the end it is passed to the API in an `Idempotency-Key` header. Since I am unofficially copying the Node SDK on these, I would prefer to keep it as it is.
