### ISSUE TITLE
standalone installation

### ISSUE THREAD

**Issue by artknight** [jcberquist/stripe-cfml#33]
Hi,
I do not have ColdBox, so the installation `box install stripecfml` will not work. How can i just install it as a standalone module?

**Comment by jcberquist** [comment]
As it says in the readme, you can just clone the repository, and then instantiate the core stripe component:
```cfc
stripe = new path.to.stripecfml.stripe(
    apiKey = '',
    config = {}
);
```
You can also still use `box install stripecfml` instead of cloning the repository if you want to make use of a `box.json` file and CommandBox without using ColdBox, after installing it, you just need to create the stripe component using the above syntax.

**Comment by artknight** [comment]
@jcberquist so if i were to include `stripe.cfc` in my project what other directories would i need to include as well?

PS: I am just trying to be a minimalist with the files I import :)

**Comment by jcberquist** [comment]
Well, of the files and directories in the repository, in a non ColdBox install, you will need the `lib` subfolder (and all its contents), the `metadata` subfolder (and all its contents), and `stripe.cfc` 😀.
