### ISSUE TITLE
javacast("boolean", 1) values are converted to "YES"

### ISSUE THREAD

**Issue by JamoCA** [jcberquist/stripe-cfml#49]
I'm integrating this library for use as an API endpoint for the [Elements Javascript SDK](https://stripe.com/docs/payments/quickstart?platform=web&lang=php). _(This is a link to PHP library since they don't offer any SDKs for CFML.)_

NOTE: I'm testing this on a CF2016 server since that's the oldest version of Adobe ColdFusion that I'm still contracted to support.

I attempted to create a payment intent using this object with an explicitly-cased Java boolean value:
```js
args = [
	"amount": 1400
	,"currency": "usd"
	,"automatic_payment_methods": ["enabled": javacast("boolean", 1)]
];
paymentIntent = stripe.paymentIntents.create(argumentCollection=args);
```

The Stripe API return a 400 status code with the following response:
```json
{
  "error": {
    "message": "Invalid boolean: YES",
    "param": "automatic_payment_methods[enabled]",
    "request_log_url": "**redacted**",
    "type": "invalid_request_error"
  }
}
```

... and the Request POST body was reported as:
```json
{
    "automatic_payment_methods": {
      "enabled": "YES"
},
    "currency": "usd",
    "amount": "1400"
}
```

The API request works if `true` is used instead of `javacast("boolean", 1)`.

_NOTE: I also noticed that if I explicitly cast the amount as an integer (`javacast("int", 1400)` that the API request would wrap quotes around it and treat the numeric value as a string.  This may not be an issue, but I recall experiencing some issues in the past with some APIs where sending strings instead of the documented numeric value in JSON would throw an error._

**Comment by jcberquist** [comment]
Thanks for the report. There is currently no special handling for boolean values - what will be submitted is what CF gives as the result of a `trim()` call. I can see that does cause issues for Java booleans, though not CF ones, interestingly. As you know, it is tricky to detect that an actual boolean value has been submitted since CF will happily cast things to booleans. I could make use of the metadata to specify that fields are expected to be booleans, but that would involve a fair bit of work to track them all down. How important is javacast to your use case?

Could you say more about the javacasting of integers - "the API request would wrap quotes around it and treat the numeric value as a string" - where are you seeing this?

**Comment by JamoCA** [comment]
Ahh... you're using `trim` on all values.  That makes sense to me now.  I was reporting a separate issue and a CF Developer stated that I didn't need to use `javacast("string")` because using `trim()` [magically converts any non-string value to a string](https://github.com/kwaschny/cf_dump/pull/15#issuecomment-1572839218).

_On a separate issue, did you know that `isvalid("email")` will trim strings prior to evaluating?  I don't like this behavior. The other `isvalid` functions don't auto-trim._

I discussed "quoted numeric strings" during lunch today with my .Net brother.  _(Seriously... he's my brother and he's a .Net developer.)_  He stated that he's experienced this same issues with some APIs that pass through the decoded JSON object to internal processes that may only accept typed data. Stringifying numeric values would definitely throw errors in this case.  I personally encountered these issues when using Authorize.net's JSON-to-XML API gateway. Their API additionally required the JSON keys to be in a [very specific order](https://stackoverflow.com/a/54224138/693068).  Luckily Stripe doesn't care, but it's something that I always check whenever viewing request/response output during testing.

I use `javacast` a lot because I prefer typed data and don't want ColdFusion to guess.  If I need a largish string with numbers to remain a string (E.164 phone format, serial numbers, credit card numbers in an API), I proactively cast as a string or risk having ColdFusion munge the value as scientific notation.

**Comment by jcberquist** [comment]
Hi @JamoCA - to follow up on this: `stripe-cfml` has specific handling (not just a `trim()` call) for certain data types sent to the API. I have updated it to add such support for boolean values. If you try `v3.5.0` it should now correctly cast the java boolean to the string `true` instead of `YES`. As regards numeric strings - the Stripe API uses form-encoded bodies on POSTs - not JSON. So as far a the API is concerned it will be receiving a string like `amount=1400` in the url-encoded body of the request.
